name: Master PR Merge [Publish to npm]

on:
  pull_request:
    branches: ["master"]
    types:
      - closed
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, future-runner-01]

    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' 

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ runner.os }}-

      - name: Install pnpm
        run: npm install -g pnpm


      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: Check if react-crisp-toast has changed
        id: check_changes
        run: |
          CHANGED_FILES=$(git diff --name-only origin/master...HEAD)
          echo "Changed files: $CHANGED_FILES"
          if echo "$CHANGED_FILES" | grep -q '^core'; then
            echo "core has changed"
            echo "publish=true" >> $GITHUB_ENV
          else
            echo "No changes core"
            echo "publish=false" >> $GITHUB_ENV
          fi

      - name: Build react-crisp-toast
        env: 
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        if: env.publish == 'true'
        run: |
          cd core
          pnpm build

      - name: Publish to npm
        if: env.publish == 'true'
        run: |
          pnpm semantic-release
