name: Master PR Merge [Publish to npm]

on:
  pull_request:
    branches: ["master"]
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          clean: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
 
      - name: Build react-crisp-toast
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd react-crisp-toast
          pnpm build

      - name: Publish to npm
        run: |
          pnpm release
